server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_generator?useSSL=false&serverTimezone=UTC
    username: resume_generator
    password: 1010411661 # <-- 更改成你的账号密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  # Email Configuration
  mail:
    host: smtp.qq.com
    port: 587
    username: 1010411661@qq.com
    password: twrhmnwlvoxgbfji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 587

  profiles:
    active: prod  # 激活生产环境配置

deepseek:
  api-key: sk-ade771e428464713ad6a86407fe07fda # <-- 更改成你的Key
  base-url: https://api.deepseek.com/v1
  model: deepseek-chat

logging:
  level:
    com.resume.generator: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE 

# 自定义配置
application:
  security:
    jwt:
      # 这是一个随机生成的Base64编码的密钥，用于JWT签名。请务必保密。
      # 在生产环境中，强烈建议使用环境变量来设置此值。
      secret-key: NzgxZDU2MzM3NTczNzM3ODRhNTM2ZTcxNGE0YzRiM2I0OTI4N2EzYjM5NjYyZjc4MjY3NGExMmI3MDZlMzY1Mg==
      # JWT过期时间（毫秒），这里设置为24小时
      expiration: 86400000 
