server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:resume_generator}?useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:resume_generator}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none  # 生产环境设置为none，防止意外修改数据库结构
    show-sql: false   # 生产环境关闭SQL日志
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  # Email Configuration
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 587

deepseek:
  api-key: ${DEEPSEEK_API_KEY}
  base-url: https://api.deepseek.com/v1
  model: deepseek-chat

logging:
  file:
    name: /www/wwwlogs/resume_generator.log  # 日志文件路径
  level:
    root: WARN
    com.resume.generator: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

# 自定义配置
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 