server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_generator?useSSL=false&serverTimezone=UTC
    username: 小泥人hyper
    password: xxx # <-- 修改数据库用户名密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

deepseek:
  api-key: xxx # <-- 此处输入deepseek的Key
  base-url: https://api.deepseek.com/v1
  model: deepseek-chat

logging:
  level:
    com.resume.generator: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE 
